name: loon
url: https://github.com/andremedeiros/loon
environment:
  LOON: Was here
services:
  postgresql:
  memcached:
  redis:
languages:
  ruby:
tasks:
  build:
    description: Builds Loon
    command: |
      go generate
      go build \
        -ldflags="-X github.com/andremedeiros/loon/cmd.version=$(git rev-parse --short HEAD)"
  test:
    description: Runs go tests
    command: go test ./... -v
