name: loon
url: https://github.com/andremedeiros/loon
environment:
  LOON: Was here
services:
  postgresql:
  memcached:
  redis:
languages:
  ruby:
tasks:
  build:
    description: Builds Loon
    command: |
      go build \
        -ldflags="-X github.com/andremedeiros/loon/cmd.version=$(git rev-parse --short HEAD)"
  test:
    description: Runs go tests
    command: go test ./... -v
  generate:
    description: Generates bindata files from catalog
    command: |
      go-bindata -pkg service \
        -prefix internal/catalog/service/ \
        -o ./internal/catalog/service/bindata.go \
        internal/catalog/service/**/*.json
      go-bindata -pkg language \
        -prefix internal/catalog/language/ \
        -o ./internal/catalog/language/bindata.go \
        internal/catalog/language/**/*.json
