on: [push, pull_request]
name: Integration
jobs:
  integration:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.platform }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.14.x
    - name: Install Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7.1
        bundler-cache: true
    - name: Install Nix
      uses: cachix/install-nix-action@v10
      with:
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build Loon
      run: go build
    - name: Bundle Install
      run: bundle install
    - name: Integration Tests
      run: ruby integration/**/*_test.rb
